<script setup>
import { ref } from 'vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';

const props = defineProps({ profile:Object, applications:Array, savedJobs:Array, resumes:Array, alerts:Array, interviews:Array, metrics:Object });
const tab = ref('applications');
const profileForm = useForm({ headline:props.profile?.headline||'', bio:props.profile?.bio||'', phone:props.profile?.phone||'', city:props.profile?.city||'', country:props.profile?.country||'', visibility:props.profile?.visibility||'public' });
const resumeForm = useForm({ name:'', resume:null });
const alertForm = useForm({ name:'', filters:{ keyword:'', location:'' }, frequency:'daily' });
const statusClass = status => ({hired:'bg-emerald-100 text-emerald-700',offer:'bg-violet-100 text-violet-700',rejected:'bg-red-100 text-red-700',withdrawn:'bg-gray-100 text-gray-600',interview:'bg-blue-100 text-blue-700'}[status]||'bg-amber-100 text-amber-700');
const location = job => [job.city,job.country].filter(Boolean).join(', ')||'Remote';
const withdraw = application => confirm('Withdraw this application?') && router.patch(route('applications.withdraw',application.id));
const unsave = job => router.post(route('jobs.save',job.id),{}, {preserveScroll:true});
const upload = () => resumeForm.post(route('candidate.resumes.store'), {forceFormData:true, onSuccess:()=>resumeForm.reset()});
</script>

<template>
<Head title="Candidate Workspace"/>
<AuthenticatedLayout>
  <template #header><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-[#309689]">Candidate</p><h2 class="text-2xl font-bold">Your career workspace</h2></div><Link href="/jobs" class="rounded-lg bg-[#309689] px-5 py-2.5 text-center font-semibold text-white">Find jobs</Link></div></template>
  <div class="mx-auto max-w-7xl space-y-7 px-4 py-10 sm:px-6 lg:px-8">
    <div v-if="$page.props.flash.success" class="rounded-xl bg-emerald-50 p-4 text-emerald-800">{{$page.props.flash.success}}</div>
    <div v-if="Object.keys($page.props.errors).length" class="rounded-xl bg-red-50 p-4 text-red-700"><p v-for="error in $page.props.errors">{{error}}</p></div>
    <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article v-for="(value,label) in metrics" :key="label" class="rounded-2xl bg-white p-6 shadow-sm"><p class="text-sm text-gray-500">{{label}}</p><strong class="mt-2 block text-3xl">{{value}}</strong></article></section>
    <nav class="flex gap-2 overflow-x-auto rounded-2xl bg-white p-2 shadow-sm"><button v-for="item in ['applications','saved','profile','resumes','alerts','interviews']" :key="item" @click="tab=item" class="whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold capitalize" :class="tab===item?'bg-[#309689] text-white':'text-gray-600 hover:bg-gray-50'">{{item}}</button></nav>

    <section v-if="tab==='applications'" class="rounded-2xl bg-white shadow-sm"><div class="border-b p-6"><h3 class="text-xl font-bold">Applications</h3><p class="text-sm text-gray-500">Track every role from submission through offer.</p></div><div class="divide-y"><article v-for="application in applications" :key="application.id" class="flex flex-col justify-between gap-4 p-6 md:flex-row md:items-center"><div><Link :href="`/jobs/${application.job_listing.slug}`" class="font-bold hover:text-[#309689]">{{application.job_listing.title}}</Link><p class="mt-1 text-sm text-gray-500">{{application.job_listing.company.name}} · {{location(application.job_listing)}}</p><small class="text-gray-400">Applied {{new Date(application.submitted_at).toLocaleDateString()}}</small></div><div class="flex items-center gap-3"><span class="rounded-full px-3 py-1 text-xs font-bold capitalize" :class="statusClass(application.status)">{{application.status}}</span><button v-if="!['withdrawn','rejected','hired'].includes(application.status)" @click="withdraw(application)" class="text-sm font-semibold text-red-600">Withdraw</button></div></article><p v-if="!applications.length" class="p-12 text-center text-gray-500">You have not applied for a job yet.</p></div></section>

    <section v-if="tab==='saved'" class="grid gap-5 md:grid-cols-2"><article v-for="job in savedJobs" :key="job.id" class="rounded-2xl bg-white p-6 shadow-sm"><span class="text-xs font-bold uppercase text-[#309689]">{{job.category?.name}}</span><Link :href="`/jobs/${job.slug}`" class="mt-2 block text-xl font-bold">{{job.title}}</Link><p class="mt-1 text-gray-500">{{job.company.name}} · {{location(job)}}</p><div class="mt-5 flex gap-3"><Link :href="`/jobs/${job.slug}`" class="rounded-lg bg-[#309689] px-4 py-2 text-sm font-bold text-white">View job</Link><button @click="unsave(job)" class="rounded-lg border px-4 py-2 text-sm font-bold text-red-600">Remove</button></div></article><p v-if="!savedJobs.length" class="rounded-2xl bg-white p-12 text-center text-gray-500 md:col-span-2">No saved jobs yet.</p></section>

    <section v-if="tab==='profile'" class="rounded-2xl bg-white p-7 shadow-sm"><h3 class="text-xl font-bold">Candidate profile</h3><form @submit.prevent="profileForm.patch(route('candidate.profile'))" class="mt-6 grid gap-5 md:grid-cols-2"><label class="field"><span>Professional headline</span><input v-model="profileForm.headline" placeholder="Senior product designer"></label><label class="field"><span>Phone</span><input v-model="profileForm.phone"></label><label class="field"><span>City</span><input v-model="profileForm.city"></label><label class="field"><span>Country</span><input v-model="profileForm.country"></label><label class="field md:col-span-2"><span>Professional bio</span><textarea v-model="profileForm.bio" rows="6"></textarea></label><label class="field"><span>Profile visibility</span><select v-model="profileForm.visibility"><option value="public">Public</option><option value="employers">Employers only</option><option value="private">Private</option></select></label><div class="md:col-span-2"><button class="rounded-lg bg-[#309689] px-5 py-3 font-bold text-white" :disabled="profileForm.processing">Save profile</button></div></form></section>

    <section v-if="tab==='resumes'" class="grid gap-6 lg:grid-cols-3"><form @submit.prevent="upload" class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="text-xl font-bold">Upload résumé</h3><label class="field mt-5"><span>Document name</span><input v-model="resumeForm.name" required placeholder="Product résumé"></label><label class="field mt-4"><span>PDF, DOC or DOCX · max 5 MB</span><input type="file" required accept=".pdf,.doc,.docx" @change="resumeForm.resume=$event.target.files[0]"></label><button class="mt-5 w-full rounded-lg bg-[#309689] py-3 font-bold text-white">Upload</button></form><div class="space-y-4 lg:col-span-2"><article v-for="resume in resumes" :key="resume.id" class="flex items-center justify-between rounded-2xl bg-white p-5 shadow-sm"><div><b>{{resume.name}}</b><p class="text-xs text-gray-400">Uploaded {{new Date(resume.created_at).toLocaleDateString()}}</p></div><div class="flex items-center gap-3"><span v-if="resume.is_default" class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">Default</span><button v-else @click="router.patch(route('candidate.resumes.default',resume.id))" class="text-sm font-bold text-[#309689]">Make default</button><button @click="confirm('Delete this résumé?')&&router.delete(route('candidate.resumes.destroy',resume.id))" class="text-sm font-bold text-red-600">Delete</button></div></article><p v-if="!resumes.length" class="rounded-2xl bg-white p-10 text-center text-gray-500">Upload a résumé to make applications faster.</p></div></section>

    <section v-if="tab==='alerts'" class="grid gap-6 lg:grid-cols-3"><form @submit.prevent="alertForm.post(route('job-alerts.store'),{onSuccess:()=>alertForm.reset()})" class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="text-xl font-bold">Create job alert</h3><label class="field mt-4"><span>Alert name</span><input v-model="alertForm.name" required></label><label class="field mt-4"><span>Keyword</span><input v-model="alertForm.filters.keyword"></label><label class="field mt-4"><span>Location</span><input v-model="alertForm.filters.location"></label><label class="field mt-4"><span>Frequency</span><select v-model="alertForm.frequency"><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><button class="mt-5 w-full rounded-lg bg-[#309689] py-3 font-bold text-white">Create alert</button></form><div class="space-y-4 lg:col-span-2"><article v-for="alert in alerts" :key="alert.id" class="flex items-center justify-between rounded-2xl bg-white p-5 shadow-sm"><div><b>{{alert.name}}</b><p class="text-sm text-gray-500">{{alert.filters?.keyword||'All jobs'}} · {{alert.filters?.location||'Any location'}} · {{alert.frequency}}</p></div><div class="flex gap-3"><button @click="router.patch(route('candidate.alerts.toggle',alert.id))" class="text-sm font-bold" :class="alert.active?'text-emerald-600':'text-gray-400'">{{alert.active?'Active':'Paused'}}</button><button @click="router.delete(route('candidate.alerts.destroy',alert.id))" class="text-sm font-bold text-red-600">Delete</button></div></article><p v-if="!alerts.length" class="rounded-2xl bg-white p-10 text-center text-gray-500">Create an alert to hear about matching roles.</p></div></section>

    <section v-if="tab==='interviews'" class="space-y-4"><article v-for="interview in interviews" :key="interview.id" class="flex flex-col justify-between gap-4 rounded-2xl bg-white p-6 shadow-sm md:flex-row md:items-center"><div><span class="text-xs font-bold uppercase text-[#309689]">{{interview.type}} interview</span><h3 class="mt-1 text-lg font-bold">{{interview.job_title}}</h3><p class="text-gray-500">{{interview.company_name}}</p></div><div class="md:text-right"><b>{{new Date(interview.scheduled_at).toLocaleString()}}</b><p class="text-sm text-gray-500">{{interview.location_or_url||'Details to follow'}}</p></div></article><p v-if="!interviews.length" class="rounded-2xl bg-white p-12 text-center text-gray-500">Scheduled interviews will appear here.</p></section>
  </div>
</AuthenticatedLayout>
</template>

<style scoped>
.field{display:flex;flex-direction:column;gap:.4rem}.field span{font-size:.75rem;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:#6b7280}.field input,.field textarea,.field select{border-radius:.65rem;border-color:#d1d5db}.field input:focus,.field textarea:focus,.field select:focus{border-color:#309689;box-shadow:0 0 0 1px #309689}
</style>
