<?php
namespace App\Http\Controllers;
use App\Models\Company;
use App\Models\JobListing;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
class EmployerJobController extends Controller {
 public function store(Request $r){$data=$r->validate(['company_id'=>'required|exists:companies,id','job_category_id'=>'nullable|exists:job_categories,id','title'=>'required|max:150','description'=>'required','responsibilities'=>'nullable','requirements'=>'nullable','employment_type'=>'required','workplace_type'=>'required','city'=>'nullable','country'=>'nullable','salary_min'=>'nullable|integer|min:0','salary_max'=>'nullable|integer|gte:salary_min','application_deadline'=>'nullable|date|after:today','application_type'=>'required|in:internal,external','external_url'=>'nullable|required_if:application_type,external|url']);$company=Company::findOrFail($data['company_id']);abort_unless($company->owner_id===$r->user()->id||$company->members()->whereKey($r->user()->id)->exists(),403);$data['created_by']=$r->user()->id;$data['slug']=Str::slug($data['title']).'-'.Str::lower(Str::random(6));$data['status']='pending';return back()->with('success',JobListing::create($data)->title.' submitted for review.');}
 public function update(Request $r,JobListing $job){abort_unless($job->created_by===$r->user()->id||$r->user()->isAdmin(),403);$data=$r->validate(['company_id'=>'sometimes|required|exists:companies,id','job_category_id'=>'nullable|exists:job_categories,id','title'=>'sometimes|required|max:150','description'=>'sometimes|required','responsibilities'=>'nullable','requirements'=>'nullable','employment_type'=>'sometimes|required','workplace_type'=>'sometimes|required','city'=>'nullable','country'=>'nullable','salary_min'=>'nullable|integer|min:0','salary_max'=>'nullable|integer|gte:salary_min','application_deadline'=>'nullable|date','application_type'=>'sometimes|required|in:internal,external','external_url'=>'nullable|required_if:application_type,external|url','status'=>'sometimes|in:draft,pending,closed']);if(isset($data['title']))$data['slug']=Str::slug($data['title']).'-'.$job->id;if($job->status==='rejected')$data['status']='pending';$job->update($data);return redirect()->route('employer.workspace')->with('success','Job updated.');}
 public function destroy(Request $r,JobListing $job){abort_unless($job->created_by===$r->user()->id,403);$job->delete();return back()->with('success','Job deleted.');}
}
