<script setup>
import { ref } from 'vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
defineProps({metrics:Object,pendingJobs:Array,publishedJobs:Array,companies:Array,users:Array,userFilters:Object,reports:Array,subscriptions:Array,categories:Array,skills:Array,auditLogs:Array});
const tab=ref('moderation');const category=useForm({name:''});const skill=useForm({name:''});
const moderate=(job,status)=>router.patch(route('admin.jobs.moderate',job.id),{status,note:status==='rejected'?prompt('Reason for rejection (optional)')||'':''},{preserveScroll:true});
const verify=(company,status)=>router.patch(route('admin.companies.verify',company.id),{status},{preserveScroll:true});
const updateUser=(user,data)=>router.patch(route('admin.users.update',user.id),data,{preserveScroll:true});
const search=e=>router.get(route('admin.workspace'),{q:e.target.value},{preserveState:true,replace:true});
const badge=value=>value==='published'||value==='verified'||value==='active'||value==='resolved'?'bg-emerald-100 text-emerald-700':value==='rejected'||value==='suspended'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700';
</script>
<template><Head title="Admin Control Panel"/><AuthenticatedLayout><template #header><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-[#309689]">Administration</p><h2 class="text-2xl font-bold">Platform control panel</h2></div><Link href="/jobs" class="rounded-lg border border-[#309689] px-4 py-2 text-center font-bold text-[#309689]">View marketplace</Link></div></template>
<div class="mx-auto max-w-7xl space-y-7 px-4 py-10 sm:px-6 lg:px-8"><div v-if="$page.props.flash.success" class="rounded-xl bg-emerald-50 p-4 text-emerald-800">{{$page.props.flash.success}}</div><div v-if="Object.keys($page.props.errors).length" class="rounded-xl bg-red-50 p-4 text-red-700"><p v-for="error in $page.props.errors">{{error}}</p></div>
<section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article v-for="(value,label) in metrics" class="rounded-2xl bg-white p-6 shadow-sm"><p class="text-sm text-gray-500">{{label}}</p><strong class="mt-2 block text-3xl">{{value}}</strong></article></section>
<nav class="flex gap-2 overflow-x-auto rounded-2xl bg-white p-2 shadow-sm"><button v-for="item in ['moderation','companies','users','reports','billing','taxonomy','audit']" @click="tab=item" class="whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold capitalize" :class="tab===item?'bg-[#309689] text-white':'text-gray-600 hover:bg-gray-50'">{{item}}</button></nav>

<section v-if="tab==='moderation'" class="space-y-6"><div class="rounded-2xl bg-white shadow-sm"><header class="border-b p-6"><h3 class="text-xl font-bold">Pending job moderation</h3><p class="text-sm text-gray-500">Review listings before they become public.</p></header><div class="divide-y"><article v-for="job in pendingJobs" class="flex flex-col justify-between gap-5 p-6 lg:flex-row lg:items-center"><div><span class="text-xs font-bold uppercase text-[#309689]">{{job.company.name}}</span><h4 class="mt-1 text-lg font-bold">{{job.title}}</h4><p class="mt-2 max-w-3xl text-sm text-gray-500 line-clamp-2">{{job.description}}</p><small class="text-gray-400">Submitted by {{job.creator.name}} · {{new Date(job.created_at).toLocaleDateString()}}</small></div><div class="flex gap-2"><button @click="moderate(job,'published')" class="action primary">Publish</button><button @click="moderate(job,'rejected')" class="action danger">Reject</button></div></article><p v-if="!pendingJobs.length" class="p-12 text-center text-gray-500">Moderation queue is clear.</p></div></div><div class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="text-xl font-bold">Published and featured jobs</h3><div class="mt-4 grid gap-3 md:grid-cols-2"><div v-for="job in publishedJobs" class="flex items-center justify-between rounded-xl border p-4"><div><b>{{job.title}}</b><p class="text-xs text-gray-500">{{job.company.name}}</p></div><button @click="router.patch(route('admin.jobs.feature',job.id))" class="text-xl" :title="job.is_featured?'Unfeature job':'Feature job'">{{job.is_featured?'★':'☆'}}</button></div></div></div></section>

<section v-if="tab==='companies'" class="grid gap-4 md:grid-cols-2"><article v-for="company in companies" class="rounded-2xl bg-white p-6 shadow-sm"><div class="flex justify-between gap-4"><div><span class="rounded-full px-3 py-1 text-xs font-bold capitalize" :class="badge(company.verification_status)">{{company.verification_status}}</span><h3 class="mt-3 text-lg font-bold">{{company.name}}</h3><p class="text-sm text-gray-500">{{company.industry||'Industry not provided'}} · {{company.jobs_count}} jobs</p></div><button @click="router.patch(route('admin.companies.feature',company.id))" class="text-2xl" :title="company.is_featured?'Remove featured':'Feature company'">{{company.is_featured?'★':'☆'}}</button></div><p class="mt-4 text-sm text-gray-600">{{company.description||'No company description.'}}</p><div class="mt-5 flex gap-2"><button @click="verify(company,'verified')" class="action primary">Verify</button><button @click="verify(company,'rejected')" class="action danger">Reject</button></div></article></section>

<section v-if="tab==='users'" class="rounded-2xl bg-white shadow-sm"><header class="border-b p-6"><h3 class="text-xl font-bold">User management</h3><input :value="userFilters.q" @change="search" placeholder="Search name or email" class="mt-4 w-full max-w-md rounded-lg border-gray-300"></header><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="p-4">User</th><th>Role</th><th>Status</th><th>Joined</th></tr></thead><tbody><tr v-for="user in users" class="border-t"><td class="p-4"><b>{{user.name}}</b><small class="block text-gray-500">{{user.email}}</small></td><td><select :value="user.role" @change="updateUser(user,{role:$event.target.value})" class="rounded-lg border-gray-300 text-sm"><option v-for="r in ['candidate','employer','admin']">{{r}}</option></select></td><td><select :value="user.status" @change="updateUser(user,{status:$event.target.value})" class="rounded-lg border-gray-300 text-sm"><option value="active">active</option><option value="suspended">suspended</option></select></td><td>{{new Date(user.created_at).toLocaleDateString()}}</td></tr></tbody></table></div></section>

<section v-if="tab==='reports'" class="rounded-2xl bg-white shadow-sm"><header class="border-b p-6"><h3 class="text-xl font-bold">Reports and abuse queue</h3></header><div class="divide-y"><article v-for="report in reports" class="flex flex-col justify-between gap-4 p-6 md:flex-row md:items-center"><div><span class="rounded-full px-3 py-1 text-xs font-bold capitalize" :class="badge(report.status)">{{report.status}}</span><h4 class="mt-3 font-bold">{{report.reason}}</h4><p class="text-sm text-gray-500">{{report.details||'No additional details'}} · Reported by {{report.reporter_name}}</p></div><select :value="report.status" @change="router.patch(route('admin.reports.update',report.id),{status:$event.target.value})" class="rounded-lg border-gray-300"><option value="open">open</option><option value="reviewing">reviewing</option><option value="resolved">resolved</option><option value="dismissed">dismissed</option></select></article><p v-if="!reports.length" class="p-12 text-center text-gray-500">No reports have been submitted.</p></div></section>

<section v-if="tab==='billing'" class="rounded-2xl bg-white shadow-sm"><header class="border-b p-6"><h3 class="text-xl font-bold">Dummy payment subscriptions</h3><p class="text-sm text-gray-500">Read-only visibility into simulated employer billing.</p></header><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="p-4">Company</th><th>Plan</th><th>Amount</th><th>Reference</th><th>Status</th><th>Started</th></tr></thead><tbody><tr v-for="sub in subscriptions" class="border-t"><td class="p-4 font-bold">{{sub.company.name}}</td><td>{{sub.plan.name}}</td><td>${{(sub.plan.price_cents/100).toFixed(2)}}</td><td class="font-mono text-xs">{{sub.dummy_reference}}</td><td><span class="rounded-full px-3 py-1 text-xs font-bold" :class="badge(sub.status)">{{sub.status}}</span></td><td>{{new Date(sub.starts_at).toLocaleDateString()}}</td></tr></tbody></table><p v-if="!subscriptions.length" class="p-12 text-center text-gray-500">No dummy subscriptions yet.</p></div></section>

<section v-if="tab==='taxonomy'" class="grid gap-6 lg:grid-cols-2"><div class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="text-xl font-bold">Job categories</h3><form @submit.prevent="category.post(route('admin.categories.store'),{onSuccess:()=>category.reset()})" class="mt-4 flex gap-2"><input v-model="category.name" required placeholder="New category" class="min-w-0 flex-1 rounded-lg border-gray-300"><button class="action primary">Add</button></form><div class="mt-5 divide-y"><div v-for="item in categories" class="flex items-center justify-between py-3"><span>{{item.name}} <small class="text-gray-400">({{item.jobs_count}} jobs)</small></span><button @click="router.delete(route('admin.categories.destroy',item.id))" class="text-sm font-bold text-red-600" :disabled="item.jobs_count">Delete</button></div></div></div><div class="rounded-2xl bg-white p-6 shadow-sm"><h3 class="text-xl font-bold">Skills</h3><form @submit.prevent="skill.post(route('admin.skills.store'),{onSuccess:()=>skill.reset()})" class="mt-4 flex gap-2"><input v-model="skill.name" required placeholder="New skill" class="min-w-0 flex-1 rounded-lg border-gray-300"><button class="action primary">Add</button></form><div class="mt-5 flex flex-wrap gap-2"><span v-for="item in skills" class="rounded-full bg-gray-100 px-3 py-2 text-sm">{{item.name}} <button @click="router.delete(route('admin.skills.destroy',item.id))" class="ml-2 text-red-600">×</button></span></div></div></section>

<section v-if="tab==='audit'" class="rounded-2xl bg-white shadow-sm"><header class="border-b p-6"><h3 class="text-xl font-bold">Audit history</h3><p class="text-sm text-gray-500">Recent sensitive administrative actions.</p></header><div class="divide-y"><article v-for="log in auditLogs" class="grid gap-2 p-5 text-sm md:grid-cols-4"><b>{{log.action}}</b><span>{{log.user_name||'System'}}</span><span class="text-gray-500">{{log.auditable_type?.split('\\').pop()}} #{{log.auditable_id}}</span><time class="text-gray-400 md:text-right">{{new Date(log.created_at).toLocaleString()}}</time></article><p v-if="!auditLogs.length" class="p-12 text-center text-gray-500">No administrative actions recorded.</p></div></section>
</div></AuthenticatedLayout></template>
<style scoped>.action{border-radius:.55rem;padding:.55rem 1rem;font-size:.875rem;font-weight:700}.primary{background:#309689;color:white}.danger{background:#fee2e2;color:#b91c1c}button:disabled{cursor:not-allowed;opacity:.4}</style>
